export const REACT_QUERY_KEYS = {
  COURSES: 'COURSES',
  CREATE_COURSE: 'CREATE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  GET_COURSE_BY_ID: 'GET_COURSE_BY_ID',
  DELETE_COURSE: 'DELETE_COURSE',
};

export const DEFAULT_PAGINATION = {
  PAGE: 0,
  SIZE: 20,
};
