export const REACT_QUERY_KEYS = {
  USERS: 'USERS',
  DELETE_USER: 'DELETE_USER',
  CREATE_USER: 'CREATE_USER',
  INVITE_USER: 'INVITE_USER',
  UPDATE_USER: 'UPDATE_USER',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_USER_BY_EMAIL: 'GET_USER_BY_EMAIL',
  CERTIFICATES: 'CERTIFICATES',
  COURSE_CERTIFICATE: 'COURSE_CERTIFICATE',
};

export const DEFAULT_PAGINATION = {
  PAGE: 0,
  SIZE: 20,
};
