export interface IAction {
  type: string;
  args?: any;
}

export enum ActionEnum {
  SELECT_ENTITY = 'SELECT_ENTITY',
  SELECT_ENTITIES = 'SELECT_ENTITIES',
  TOGGLE_SELECT_ENTITY = 'TOGGLE_SELECT_ENTITY',
  TOGGLE_SELECT_ENTITIES = 'TOGGLE_SELECT_ENTITIES',
  TOGGLE_SELECT_ALL_ENTITIES = 'TOGGLE_SELECT_ALL_ENTITIES',
  DELETE_ENTITY = 'DELETE_ENTITY',
  DELETE_SELECTION = 'DELETE_SELECTION',
  VIEW_ENTITY = 'VIEW_ENTITY',

  COPY = 'COPY',
  VIEW = 'VIEW',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  CLOSE = 'CLOSE',
  CLEAR = 'CLEAR',
  MOVE = 'MOVE',
}
