logging:
  level:
    ROOT: INFO
    com.endo4life: DEBUG
    com.endo4life.service: DEBUG
    com.endo4life.web.rest: DEBUG
    org.springframework.cache: TRACE
    com.endo4life: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    org.springframework.boot.devtools: ERROR
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
  com:
    fasterxml:
      jackson: DEBUG

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          [
            "configprops",
            "env",
            "health",
            "info",
            "logfile",
            "loggers",
            "prometheus",
            "threaddump",
            "caches",
          ]

application:
  app-version: @project.version@

spring:
  task:
    execution:
      thread-name-prefix: endo4life-task-
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 1000
    scheduling:
      thread-name-prefix: endo4life-scheduling-
      pool:
        size: 2
  application:
    name: endo4life-service
    keycloak-configuration:
      base-url: ${KEYCLOAK_BASE_URL:https://keycloak.mydevopsproject2023.id.vn}
      internal-url: ${KEYCLOAK_INTERNAL_URL:https://keycloak.mydevopsproject2023.id.vn}
      realm: ${KEYCLOAK_REALM:endo4life}
      client-id: ${KEYCLOAK_CLIENT_ID:endo4life_app}
      secret: ${KEYCLOAK_CLIENT_SECRET:0LsxczPTGzHaGeZI8N9mIWn0XbtNfF4d}
      jwk-set-uri: ${KEYCLOAK_BASE_URL:https://keycloak.mydevopsproject2023.id.vn}/realms/${KEYCLOAK_REALM:endo4life}/protocol/openid-connect/certs
      issuer-uri: ${KEYCLOAK_BASE_URL:https://keycloak.mydevopsproject2023.id.vn}/realms/${KEYCLOAK_REALM:endo4life}
      webhook:
        enabled: true
        client-id: endo4life_app
        realm: endo4life
        secret: ${KEYCLOAK_WEBHOOK_SECRET:0LsxczPTGzHaGeZI8N9mIWn0XbtNfF4d}
        path: https://api.mydevopsproject2023.id.vn/api/v1/webhooks/keycloak
      invite-lifespan: 432000
    minio-configuration:
      endpoint: https://minio-api.mydevopsproject2023.id.vn
      username: ${MINIO_USERNAME:endo4life}
      password: ${MINIO_PASSWORD:U6ZeyWQKjLMA6t31lh4xdebjkhkCs6x9}
      webhook-identifier: _
      bucket-video: videos
      bucket-image: images
      bucket-avatar: avatars
      bucket-thumbnail: thumbnails
      bucket-other: others
      bucket-process: process
    job:
      delete-user:
        enabled: true
        cron: 0 0 * * * *
  datasource:
    url: jdbc:postgresql://${DB_HOST:3.107.208.12}:${DB_PORT:5432}/${DB_NAME:elearning}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres123}
    driverClassName: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 51200MB
      resolve-lazily: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL:https://keycloak.mydevopsproject2023.id.vn}/realms/${KEYCLOAK_REALM:endo4life}
          jwk-set-uri: ${KEYCLOAK_BASE_URL:https://keycloak.mydevopsproject2023.id.vn}/realms/${KEYCLOAK_REALM:endo4life}/protocol/openid-connect/certs

# Trust all certificates for development (NOT for production)
trust:
  store: ${TRUST_STORE:}
  store-password: ${TRUST_STORE_PASSWORD:}