export const REACT_QUERY_KEYS = {
  COMMENTS: 'COMMENTS',
  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  GET_COMMENT_BY_ID: 'GET_COMMENT_BY_ID',
  DELETE_COMMENT: 'DELETE_COMMENT',
};
