export const REACT_QUERY_KEYS = {
  COMMENTS: 'COMMENTS',
  CREATE_COMMENT: 'CREATE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  GET_COMMENT_BY_ID: 'GET_COMMENT_BY_ID',
  DELETE_COMMENT: 'DELETE_COMMENT',
  DOCTOR_USER_CONVERSATIONS: 'DOCTOR_USER_CONVERSATIONS',
  CREATE_DOCTOR_USER_CONVERSATION: 'CREATE_DOCTOR_USER_CONVERSATION',
  UPDATE_DOCTOR_USER_CONVERSATION: 'UPDATE_DOCTOR_USER_CONVERSATION',
  GET_DOCTOR_USER_CONVERSATION_BY_ID: 'GET_DOCTOR_USER_CONVERSATION_BY_ID',
  DELETE_DOCTOR_USER_CONVERSATION: 'DELETE_DOCTOR_USER_CONVERSATION',
};
