export const STUDENT_WEB_ROUTES = {
  ROOT: '/',
  HOME: '/',
  RESOURCES: '/resources',
  RESOURCE_IMAGE: '/resources/images/:id',
  RESOURCE_VIDEO: '/resources/videos/:id',
  RESOURCE_COURSE: '/resources/courses/:id',
  MY_LEARNING: '/my-learning',
  MY_LEARNING_PROGRESS: '/my-learning/progress',
  WATCH_HISTORY: '/watch-history',
  COURSE_LECTURE: '/resources/courses/:courseId/lectures/:lectureId',
  COURSE_ENTRANCE_TEST: '/resources/courses/:courseId/entrance-test',
  COURSE_LECTURE_REVIEW: '/resources/courses/:courseId/lectures/:lectureId/review',
  COURSE_FINAL_EXAM: '/resources/courses/:courseId/final-exam',
  MY_LIBRARY: '/my-library',
  ABOUT_US: '/about-us',
  MY_PROFILE: '/my-profile',
  NOT_FOUND: '/not-found',
};
