export const REACT_QUERY_KEYS = {
  COURSE_SECTIONS: 'COURSE_SECTIONS',
  CREATE_COURSE_SECTION: 'CREATE_COURSE_SECTION',
  UPDATE_COURSE_SECTION: 'UPDATE_COURSE_SECTION',
  GET_COURSE_SECTION_BY_ID: 'GET_COURSE_SECTION_BY_ID',
  DELETE_COURSE_SECTION: 'DELETE_COURSE_SECTION',
};

export const DEFAULT_PAGINATION = {
  PAGE: 0,
  SIZE: 20,
};
